<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Jalankan seeder database.
     */
    public function run(): void
    {
        DB::table('barangs')->insert([
            [
                'id' => 1,
                'kode_barang' => 'B001',
                'nama_barang' => 'Monitor SPC',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'jumlah' => 24,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759734379_monitor2.jpg',
                'created_at' => '2025-10-05 17:00:34',
                'updated_at' => '2025-10-05 17:09:04',
            ],
            [
                'id' => 2,
                'kode_barang' => 'B002',
                'nama_barang' => 'Mouse Genius',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'jumlah' => 24,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759734435_mouse2.jpg',
                'created_at' => '2025-10-05 17:07:15',
                'updated_at' => '2025-10-05 17:08:53',
            ],
            [
                'id' => 3,
                'kode_barang' => 'B003',
                'nama_barang' => 'Keyboard',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'jumlah' => 24,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759734473_keyboard2.jpg',
                'created_at' => '2025-10-05 17:07:53',
                'updated_at' => '2025-10-05 17:08:37',
            ],
            [
                'id' => 4,
                'kode_barang' => 'B004',
                'nama_barang' => 'CPU',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'jumlah' => 24,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759734507_cpu2.jpg',
                'created_at' => '2025-10-05 17:08:27',
                'updated_at' => '2025-10-05 17:08:27',
            ],
            [
                'id' => 5,
                'kode_barang' => 'B005',
                'nama_barang' => 'Stabilizer Stavol Matsunaga',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 19,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759734670_stavol2.jpg',
                'created_at' => '2025-10-05 17:11:10',
                'updated_at' => '2025-10-05 17:11:10',
            ],
            [
                'id' => 6,
                'kode_barang' => 'B006',
                'nama_barang' => 'Mouse Pad Rexus',
                'kategori_id' => 1,
                'lokasi_id' => 2,
                'jumlah' => 24,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:22:17',
                'updated_at' => '2025-10-05 17:22:17',
            ],
            [
                'id' => 7,
                'kode_barang' => 'B007',
                'nama_barang' => 'Kipas',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 3,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:23:35',
                'updated_at' => '2025-10-05 17:23:35',
            ],
            [
                'id' => 8,
                'kode_barang' => 'B008',
                'nama_barang' => 'Keyboard Fantech',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'jumlah' => 3,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:27:46',
                'updated_at' => '2025-10-05 17:27:46',
            ],
            [
                'id' => 9,
                'kode_barang' => 'B009',
                'nama_barang' => 'CCTV',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:29:20',
                'updated_at' => '2025-10-05 17:29:20',
            ],
            [
                'id' => 10,
                'kode_barang' => 'B010',
                'nama_barang' => 'Lampu',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 2,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:31:03',
                'updated_at' => '2025-10-05 17:31:03',
            ],
            [
                'id' => 11,
                'kode_barang' => 'B011',
                'nama_barang' => 'AC',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:31:49',
                'updated_at' => '2025-10-05 17:31:49',
            ],
            [
                'id' => 12,
                'kode_barang' => 'B012',
                'nama_barang' => 'Kursi Siswa',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'jumlah' => 30,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:33:04',
                'updated_at' => '2025-10-05 17:33:04',
            ],
            [
                'id' => 13,
                'kode_barang' => 'B013',
                'nama_barang' => 'Meja Siswa',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'jumlah' => 30,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:33:48',
                'updated_at' => '2025-10-05 17:33:48',
            ],
            [
                'id' => 14,
                'kode_barang' => 'B014',
                'nama_barang' => 'Papan Tulis',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'jumlah' => 1,
                'satuan' => 'Buah',
                'kondisi' => 'Rusak Ringan',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:34:56',
                'updated_at' => '2025-10-05 17:34:56',
            ],
            [
                'id' => 15,
                'kode_barang' => 'B015',
                'nama_barang' => 'Kursi Guru',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'jumlah' => 2,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:35:33',
                'updated_at' => '2025-10-05 17:35:33',
            ],
            [
                'id' => 16,
                'kode_barang' => 'B016',
                'nama_barang' => 'Proyektor',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => null,
                'created_at' => '2025-10-05 17:37:34',
                'updated_at' => '2025-10-05 17:37:34',
            ],
            [
                'id' => 17,
                'kode_barang' => 'B017',
                'nama_barang' => 'Lemari',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'jumlah' => 1,
                'satuan' => 'Buah',
                'kondisi' => 'Baik',
                'tanggal_pengadaan' => '2025-10-06',
                'gambar' => '1759798726_iconmonstr-magnifier-lined-240.png',
                'created_at' => '2025-10-05 17:47:17',
                'updated_at' => '2025-10-06 10:58:46',
            ],
        ]);
    }
}
